// Developer-only build. Participants use the committed bundle, never npm.
import { build } from 'esbuild';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../../plugin/assets/pdf');
const result = await build({
  absWorkingDir: here, entryPoints: ['render.js'], bundle: true,
  format: 'iife', target: ['chrome110'], minify: true, legalComments: 'inline',
  outfile: join(out, 'render.js'), metafile: true,
});
const fontRoot = join(here, 'node_modules/@fontsource-variable/noto-sans-kr');
let fonts = await readFile(join(fontRoot, 'index.css'), 'utf8');
for (const match of [...fonts.matchAll(/url\((\.\/files\/[^)]+)\)/g)]) {
  const bytes = await readFile(join(fontRoot, match[1]));
  fonts = fonts.replace(match[0], `url(data:font/woff2;base64,${bytes.toString('base64')})`);
}
fonts = fonts.replaceAll('font-display: swap', 'font-display: block');
await writeFile(join(out, 'fonts.css'), fonts);

// Bundle upstream notices for every package actually compiled into the runtime.
const packages = new Set(['@fontsource-variable/noto-sans-kr']);
for (const file of Object.keys(result.metafile.inputs)) {
  const match = file.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
  if (match) packages.add(match[1]);
}
let notices = '# PDF runtime third-party notices\n\nGenerated by tools/pdf-assets/build.mjs. '
  + 'Sparker layout and integration are authored in this repository. '
  + 'No pdfcn, shadcn, Tremor, or Lieflat source is copied into this bundle.\n';
const versions = {};
for (const name of [...packages].sort()) {
  const root = join(here, 'node_modules', name);
  const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
  const files = (await readdir(root)).filter(x => /^(license|licence|copying|notice)([.-]|$)/i.test(x));
  // Some upstream npm packages keep their full license only in README.md.
  if (!files.length) {
    const readme = await readFile(join(root, 'README.md'), 'utf8');
    const start = readme.search(/^#+ .*license/im);
    if (start < 0 || !readme.slice(start).includes('Permission is hereby granted'))
      throw new Error(`Missing upstream license for ${name}`);
    notices += `\n\n## ${name} ${pkg.version}\n${readme.slice(start)}\n`;
  }
  versions[name] = { version: pkg.version, license: pkg.license };
  notices += `\n\n## ${name} ${pkg.version} (${pkg.license})\n`;
  for (const file of files) notices += `\n### ${file}\n\n${await readFile(join(root, file), 'utf8')}\n`;
}
await writeFile(join(out, 'THIRD_PARTY_NOTICES.md'), notices);
const sha = async file => createHash('sha256').update(await readFile(join(out, file))).digest('hex');
await writeFile(join(out, 'manifest.json'), JSON.stringify({
  format: 1, versions,
  sha256: Object.fromEntries(await Promise.all(
    ['render.js', 'fonts.css', 'print.css', 'THIRD_PARTY_NOTICES.md'].map(async x => [x, await sha(x)]))),
}, null, 2) + '\n');
console.log('Built offline PDF assets and upstream notices.');
